declare module '@inlet/react-pixi'
declare module 'react-pixi-fiber'
declare module 'react/cjs/react.production.min.js'
declare module 'react-pixi-fiber/cjs/react-pixi-fiber.production.min.js'
declare module '@inlet/react-pixi/dist/react-pixi.production.es5.js'
